SELECT BOOK_ID,
       TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE >= DATE '2021-01-01'
  AND PUBLISHED_DATE < DATE '2022-01-01'
  AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;