SELECT P.PRODUCT_CODE, 
       (OS.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT P
JOIN 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) OS
ON P.PRODUCT_ID = OS.PRODUCT_ID 
ORDER BY (OS.SALES_AMOUNT * P.PRICE) DESC, 
          P.PRODUCT_CODE ASC;
