SELECT RI.FOOD_TYPE, 
       RI.REST_ID, 
       RI.REST_NAME, 
       A.FAVORITES
FROM REST_INFO RI
JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO 
        GROUP BY FOOD_TYPE
    ) A
ON RI.FOOD_TYPE = A.FOOD_TYPE
WHERE RI.FAVORITES = A.FAVORITES
ORDER BY RI.FOOD_TYPE DESC;