SELECT AI.ANIMAL_ID, 
       AI.ANIMAL_TYPE, 
       AI.NAME
FROM ANIMAL_INS AI
WHERE NOT EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS AO
    WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
          AND 
          AO.SEX_UPON_OUTCOME LIKE '%Intact%'
) 
AND AI.SEX_UPON_INTAKE LIKE '%Intact%'
ORDER BY AI.ANIMAL_ID, 
         AI.ANIMAL_TYPE, 
         AI.NAME