SELECT EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR, 
       EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH, 
       UI.GENDER, 
       COUNT(DISTINCT UI.USER_ID) AS USERS
FROM (SELECT *
      FROM USER_INFO
      WHERE GENDER IS NOT NULL
      ) UI 
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), 
         EXTRACT(MONTH FROM OS.SALES_DATE), 
         UI.GENDER
ORDER BY EXTRACT(YEAR FROM OS.SALES_DATE), 
         EXTRACT(MONTH FROM OS.SALES_DATE), 
         UI.GENDER;
