SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
       (COUNT(DISTINCT OS.USER_ID)) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT OS.USER_ID)/(
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE JOINED >= DATE '2021-01-01' 
                  AND JOINED < DATE '2022-01-01'
       ), 1) AS PURCHASED_RATIO
FROM (SELECT * 
      FROM USER_INFO
      WHERE JOINED >= DATE '2021-01-01' 
      AND JOINED < DATE '2022-01-01') UI

JOIN ONLINE_SALE OS

ON OS.USER_ID = UI.USER_ID

GROUP BY EXTRACT(YEAR FROM SALES_DATE), 
         EXTRACT(MONTH FROM SALES_DATE)
ORDER BY EXTRACT(YEAR FROM SALES_DATE) ASC, 
         EXTRACT(MONTH FROM SALES_DATE) ASC
