SELECT FH.FLAVOR
FROM (
     SELECT FLAVOR, SUM(TOTAL_ORDER) AS FH_TOTAL_ORDER
     FROM FIRST_HALF
     GROUP BY FLAVOR
     ) FH 
JOIN
     (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL_ORDER
      FROM JULY 
      GROUP BY FLAVOR) J 
     ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.FH_TOTAL_ORDER + J.J_TOTAL_ORDER) DESC
FETCH NEXT 3 ROWS ONLY

