SELECT UGU.USER_ID, 
       UGU.NICKNAME, 
       (UGB.TOTAL_PRICE) AS TOTAL_SALES
FROM (
      SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000
     ) UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
ORDER BY TOTAL_SALES;
