SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM (
    SELECT *
    FROM USED_GOODS_BOARD UGB
         JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID     
    )
GROUP BY USER_ID, NICKNAME, STATUS
HAVING SUM(PRICE) >= 700000 AND STATUS = 'DONE'
ORDER BY SUM(PRICE) ASC;