SELECT B.TOT_SCORE, 
       HR.EMP_NO, 
       HR.EMP_NAME, 
       HR.POSITION,
       HR.EMAIL
FROM HR_EMPLOYEES HR 
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS TOT_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
    ORDER BY TOT_SCORE DESC
    LIMIT 1
    ) B
WHERE HR.EMP_NO = B.EMP_NO;