SELECT DISTINCT CC.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR CC 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH 
    ON CC.CAR_ID = CH.CAR_ID
WHERE CH.START_DATE >= DATE '2022-10-01'
    AND CH.START_DATE < DATE '2022-11-01'
    AND CC.CAR_TYPE = '세단'
ORDER BY CC.CAR_ID DESC;