SELECT II.INGREDIENT_TYPE,
       SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT FLAVOR, 
             SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM FIRST_HALF 
      GROUP BY FLAVOR) FH

JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
GROUP BY II.INGREDIENT_TYPE
ORDER BY SUM(FH.TOTAL_ORDER) ASC;

