SELECT B.CATEGORY, 
       SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
       SELECT *
       FROM BOOK_SALES
       WHERE SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
       
     ) BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC