SELECT B.CATEGORY, 
       SUM(T.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
            FROM BOOK_SALES 
            WHERE SALES_DATE >= DATE '2022-01-01'
                AND SALES_DATE < DATE '2022-02-01'
            GROUP BY BOOK_ID) T
    ON B.BOOK_ID = T.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
