SELECT FP.CATEGORY, M.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM (
        SELECT CATEGORY, PRICE, PRODUCT_NAME
            FROM FOOD_PRODUCT
            WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
        )
    GROUP BY CATEGORY
    ) M
ON FP.CATEGORY = M.CATEGORY
    AND FP.PRICE = M.MAX_PRICE
ORDER BY FP.PRICE DESC;