SELECT FP.CATEGORY, A.MAX_PRICE, FP.PRODUCT_NAME 
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
     ) A
ON FP.CATEGORY = A.CATEGORY 
WHERE FP.PRICE = A.MAX_PRICE
ORDER BY A.MAX_PRICE DESC;